cluster/apps/media/calibre-web/helm-release.yaml, cluster/apps/media/calibre-web/kustomization.yaml, cluster/apps/media/calibre-web/pvc-calibre-web-config.yaml, cluster/apps/media/kustomization.yaml, cluster/base/cluster-settings.yaml
Adds calibre-web to slowpoke
**Benefits**
Unified login, scalable book interface
SqlLite issues
- fixes #
=> Calibre web

cluster/apps/downloads/downloads-pv/kustomization.yaml, cluster/apps/downloads/downloads-pv/nfs-downloads-pv.yaml, cluster/apps/downloads/kustomization.yaml, cluster/apps/downloads/qbittorrent/config-pvc.yaml, cluster/apps/downloads/qbittorrent/helm-release.yaml, cluster/apps/downloads/qbittorrent/kustomization.yaml, cluster/apps/kustomization.yaml, cluster/apps/media/calibre-web/helm-release.yaml, cluster/apps/media/lazylibrarian/helm-release.yaml
Add qbittorrent as download client. Route behind vpn-gateway exclusively
**Benefits**
VPN routed torrent client
bugs
- fixes #22 
=> Add qbittorrent and relevant pv

.github/renovate.json5
Add comma to fix syntax error
**Benefits**
Renovate will work. 
May not fix the issue
- fixes #21 
- fixes #24 
=> fix: #24 Add comma

cluster/apps/kustomization.yaml, cluster/core/kustomization.yaml, cluster/core/rook-ceph/cluster/helm-release.yaml
Scope: Rook-Ceph
Adjustment of configuration
**Benefits**
Theoretically allow it to startup to fix #91
Breakage of this currently unused thing
- fixes #91
Incomplete PR
=> Update Rook-Ceph configuration

provision/ansible/kubernetes/inventory/group_vars/kubernetes/k3s.yml, provision/ansible/kubernetes/roles/k3s.kubernetes/templates/kube-vip/kube-vip-daemonset.yaml.j2
Refactoring to comply with expected interfacing with new versions of dependencies in the provision section
**Benefits**
Things won't break
May miss something
- fixes #
=> Upstream Change adjustments

cluster/apps/media/radarr-uhd/helm-release.yaml, cluster/apps/media/radarr-uhd/pvc-config.yaml
Add radarr-uhd helm release
**Benefits**
uhd radarr and template for shifting existing instance
... bugs
- fixes #128 
=> Add Radarr UHD with rook-ceph pvc

cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/unifi-poller/helm-release.yaml, cluster/apps/monitoring/unifi-poller/kustomization.yaml
Adds unifi poller
**Benefits**
Controller monitoring
Headaches
- fixes #
=> Add unifi poller

cluster/apps/media/kustomization.yaml, cluster/apps/media/readarr-audio/helm-release.yaml, cluster/apps/media/readarr-audio/kustomization.yaml, cluster/apps/media/readarr-audio/pvc-config.yaml
Adds instance of readarr for audiobooks
**Benefits**
Moar audiobooks
scheduler issues due to rook-ceph monkeywrench 1.9.0
- fixes #
=> Add readarr-audio

cluster/apps/kube-system/kustomization.yaml, cluster/apps/kube-system/reflector/helm-release.yaml, cluster/apps/kube-system/reflector/kustomization.yaml, cluster/apps/networking/traefik/routers/error-pages.yaml, cluster/apps/networking/traefik/tls-store/default.yaml, cluster/apps/networking/wildcard-certificate/certificate.yaml
Adds secret reflection
**Benefits**
Can mirror wildcard TLS cert in other namespaces.
Then I can use traefiks IngressRoute instead of having to do custom ingress objects
Won't work if I misunderstood something
- fixes #
=> (reflector) Add secrets reflector

mkdocs.yaml, provision/ansible/kubernetes/inventory/group_vars/master/k3s.yml, provision/ansible/kubernetes/roles/os.kubernetes/tasks/security.yml
=> Small typos fixed

README.md, cluster/apps/system-upgrade/system-upgrade-controller/agent-plan.yaml, cluster/apps/system-upgrade/system-upgrade-controller/server-plan.yaml
Updates to k3s 1.24 channel (currently [1.24.1+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.24.1+k3s1))
[Kubernetes 1.24 Release Notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1240)
[The MUST READ section](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes)
**Benefits**
1.24 yay loadbalancerIPs
may break some wonky workarounds I have going on
- fixes #
=> (k3s) Update to v1.24

cluster/apps/default/minecraft/helm-release.yaml
Reverts h3mmy/bloopySphere#1708
=> Revert "feat: update docker image itzg/minecraft-server to 2022.13.0"

cluster/apps/media/kustomization.yaml, cluster/apps/media/radarr/dashboard/dashboard.json, cluster/apps/media/radarr/dashboard/kustomization.yaml, cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/radarr/kustomization.yaml, cluster/apps/media/radarr/pvc-config.yaml, cluster/apps/media/sonarr/dashboard/dashboard.json, cluster/apps/media/sonarr/dashboard/kustomization.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/sonarr/kustomization.yaml, cluster/apps/media/sonarr/pvc-config.yaml
=> (arr) Add SD sonarr and radarr to media namespace

cluster/apps/media/calibre/helm-release.yaml, cluster/apps/media/calibre/kustomization.yaml, cluster/apps/media/calibre/pvc-config.yaml
Adds calibre hr in disabled state
**Benefits**
- fixes #
=> (calibre) Add calibre

cluster/apps/kustomization.yaml, cluster/apps/kyverno/base/helm-release.yaml, cluster/apps/kyverno/base/kustomization.yaml, cluster/apps/kyverno/base/rbac.yaml, cluster/apps/kyverno/kustomization.yaml, cluster/apps/kyverno/policies/add-prom-probes.yaml, cluster/apps/kyverno/policies/kustomization.yaml, cluster/apps/kyverno/policies/remove-cpu-limit.yaml, cluster/apps/kyverno/policies/set-internal-ingress-annotations.yaml, cluster/apps/kyverno/policies/snapshot-cronjob-controller.yaml, cluster/base/flux-system/charts/helm/kustomization.yaml, cluster/base/flux-system/charts/helm/kyverno-charts.yaml
Adds controller for kyverno
**Benefits**
Kyverno policy control
Anything could happen
- fixes #
=> (kyverno) Add controller

cluster/apps/auth/authentik/authentik-postgres-db.yaml, cluster/apps/blogs/strapi/strapi-postgres.yaml, cluster/apps/home/emqx/emqx-db-auth.yaml
Reverts h3mmy/bloopySphere#2010
=> Revert "feat!: update docker image docker.io/library/postgres to 15.0"

cluster/apps/downloads/kustomization.yaml, cluster/apps/downloads/openbooks/helm-release.yaml, cluster/apps/downloads/openbooks/kustomization.yaml
Adds [OpenBooks](https://github.com/evan-buss/openbooks)
**Benefits**
- fixes #
=> (openbooks) add

cluster/crds/cert-manager/kustomization.yaml
Reverts h3mmy/bloopySphere#2962
=> Revert "feat: update docker image quay.io/jetstack/cert-manager-controller to v1.11.0"

cluster/apps/system-upgrade/system-upgrade-controller/plans/agent.yaml, cluster/apps/system-upgrade/system-upgrade-controller/plans/server.yaml
Bump to 1.27.1+k3s1
**Benefits**
- fixes #
=> Update to 1.27.1+k3s1

cluster/apps/blogs/ghost/ghost-mysql.yaml
=> Update innodb cluster to 8.1.0

cluster/core/cert-manager/README.md
Fixes #4580
**Benefits**
- fixes #
=> fixed # 4580 Update README.md

.github/renovate/allowedVersions.json5
=> fixes #4723

cluster/apps/flux-system/dashboard/kustomization.yaml
=> Update flux grafana

cluster/apps/home/zwavejs2mqtt/helm-release.yaml
This reverts commit 21c8610541ff1823cafed0e358ea0f6dad87f2e3.
Turns out, reverting didn't unbreak the corrupted store.
**Benefits**
- fixes #
=> Revert "Revert "(zwave) move off of old chart""

cluster/apps/monitoring/grafana/hr/helm-release.yaml
=> Add emqx Grafana dash

cluster/apps/home/emqx/README.md
Update link to account for emqx restructuring their docs. They don't use versioned docs in that manner.
**Benefits**
- fixes #
=> fixes #5040

cluster/apps/media/stash/app/helm-release.yaml
=> Mount certs

cluster/apps/media/stash/app/helm-release.yaml
=> Update tls mounts

cluster/apps/default/kustomization.yaml, cluster/apps/default/wiki/db/alerts/kustomization.yaml, cluster/apps/default/wiki/db/alerts/prometheus-rule.yaml, cluster/apps/default/wiki/db/backup/backup-schedule.yaml, cluster/apps/default/wiki/db/backup/kustomization.yaml, cluster/apps/default/wiki/db/backup/obc-backup-v1.yaml, cluster/apps/default/wiki/db/cluster/kustomization.yaml, cluster/apps/default/wiki/db/cluster/wiki-cnpg.yaml, cluster/apps/default/wiki/db/config/cnpg-secret.sops.yaml, cluster/apps/default/wiki/db/config/kustomization.yaml, cluster/apps/default/wiki/db/config/wiki-secret.sops.yaml, cluster/apps/default/wiki/db/ks.yaml, cluster/apps/default/wiki/kustomization.yaml
**Benefits**
Uses 1 instance and backed by ceph-storage. That way there will be block level replication, but less performant compared to data level replication.
- fixes #5770 
=> (wiki-js) Add DB

cluster/apps/storage/minio/helm-release.yaml
Reverts h3mmy/bloopySphere#5999
=> Revert "fix: update docker image quay.io/minio/minio to release.2024-01-31t20-20-33z"

cluster/apps/system-upgrade/system-upgrade-controller/plans/agent.yaml, cluster/apps/system-upgrade/system-upgrade-controller/plans/server.yaml
**Benefits**
- fixes #
Probably want to do pr#6042 first. The kube-vip manifests need to be refreshed for ipv6 support
=> Update using system upgrade controller

cluster/apps/networking/traefik/helm-release.yaml, cluster/crds/traefik/crds.yaml
Reverts h3mmy/bloopySphere#6125
=> Revert "feat: update helm chart traefik to 26.1.0"

cluster/apps/media/overseer/helm-release.yaml
=> temporarily fallback to separate plex auth

.gitignore, cluster/apps/kyverno/policies/add-gatus-endpoints.yaml, cluster/apps/kyverno/policies/kustomization.yaml, cluster/apps/monitoring/gatus/app/README.md, cluster/apps/monitoring/gatus/app/helm-release.yaml, cluster/apps/monitoring/gatus/app/kustomization.yaml, cluster/apps/monitoring/gatus/app/rbac.yaml, cluster/apps/monitoring/gatus/app/resources/config.yaml, cluster/apps/monitoring/gatus/app/secrets.sops.yaml, cluster/apps/monitoring/gatus/ks.yaml, cluster/apps/monitoring/kustomization.yaml
Add it
**Benefits**
- fixes #6331
=> fix #6331 Add Gatus

cluster/apps/auth/authentik/helm-release.yaml, cluster/apps/kyverno/policies/add-gatus-endpoints.yaml, cluster/apps/monitoring/gatus/app/resources/config.yaml
Adds group parsing to kyverno policy. Defaults to namespace value from admission review. 
**Benefits**
- fixes #
=> (gatus) Update kyverno policy to include group

cluster/apps/monitoring/gatus/app/kustomization.yaml, cluster/apps/monitoring/gatus/app/resources/external-dns-ep.yaml
=> Create pihole gatus

cluster/apps/blogs/ghost/helm-release.yaml
Reverts h3mmy/bloopySphere#6814
Image is not yet available
=> Revert "Update Docker image ghost to 5.82.12"

cluster/apps/monitoring/gatus/app/helm-release.yaml
Updates the image for validating/testing https://github.com/TwiN/gatus/pull/748
**Benefits**
- fixes #
=> switch to gatus experimental for testing

cluster/apps/vpn-gateway/helm-release.yaml
Reverts h3mmy/bloopySphere#7773
=> Revert "Update Docker image docker.io/qmcgaw/gluetun to latest"

cluster/apps/blogs/ghost/helm-release.yaml
Reverts h3mmy/bloopySphere#7858
=> Revert "Update Docker image ghost to 5.107.2"

cluster/apps/default/bloopyboi/app/config.yaml
=> update blissfest date for 2025

cluster/core/rook-ceph/rook-ceph/cluster/helm-release.yaml, cluster/core/rook-ceph/rook-ceph/operator/helm-release.yaml, cluster/core/rook-ceph/rook-ceph/tools/rook-direct-mount/deployment.yaml
=> (rook-ceph) Update v14 -> v15

cluster/apps/media/sonarr/sonarr-hd/helm-release.yaml
Reverts h3mmy/bloopySphere#8054
=> Revert "Update Docker image ghcr.io/onedr0p/sonarr-develop to 4.0.14.2938"

cluster/core/tigera-operator/helm-release.yaml
Reverts h3mmy/bloopySphere#8126
=> Revert "Update Helm chart tigera-operator to v3.30.0"

cluster/apps/monitoring/gatus/app/helm-release.yaml, cluster/apps/monitoring/gatus/app/kustomization.yaml, cluster/apps/monitoring/gatus/app/pvc-data-v1.yaml, cluster/apps/monitoring/gatus/app/resources/config.yaml
Downgrades Gatus to use sqlite instead of postgres
**Benefits**
I can troubleshoot the postgres setup without monitoring going down 
No horizontal scalability 
- fixes #
=> Gatus to sqlite

cluster/apps/auth/authentik/outposts/external-ldap/service.yaml, cluster/apps/auth/ldap/app/helm-release.yaml, cluster/apps/default/minecraft/helm-release.yaml, cluster/apps/downloads/qbittorrent/helm-release.yaml, cluster/apps/home/go2rtc/app/helm-release.yaml, cluster/apps/home/network-ups-tools/helm-release.yaml, cluster/apps/media/books/calibre/helm-release.yaml, cluster/apps/media/plex/helm-release.yaml, cluster/apps/monitoring/vector/aggregator/helm-release.yaml, cluster/apps/networking/blocky/app/helm-release.yaml, cluster/apps/networking/k8s-gateway/helm-release.yaml, cluster/apps/networking/traefik/helm-release.yaml, cluster/core/tigera-operator/bgp/filters/drop-pod-network.yaml, cluster/core/tigera-operator/bgp/filters/kustomization.yaml, docs/_snippets/links.jinja2
Updates deprecated metallb.universe.tf annotation to use metallb.io per https://metallb.io/release-notes/#version-0149
**Benefits**
- fixes #
=> (metallb) Replace metallb.universe.tf -> metallb.io

cluster/apps/media/plex/helm-release.yaml
Reverts h3mmy/bloopySphere#8168
=> Revert "Update"

cluster/apps/media/sonarr/sonarr-uhd/helm-release.yaml
Reverts h3mmy/bloopySphere#8198
=> Revert "Update Docker image ghcr.io/home-operations/sonarr to 4.0.14.2938"

cluster/apps/vpn-gateway/helm-release.yaml
Reverts h3mmy/bloopySphere#8117
=> Revert "Update Docker image ghcr.io/angelnu/pod-gateway to v1.13.0"

cluster/apps/downloads/whisparr/helm-release.yaml
Reverts h3mmy/bloopySphere#8445
=> Revert "Update Docker image ghcr.io/drag0n141/whisparr-nightly to 2.0.0.1282"

cluster/base/flux-system/flux-oci-ks.yaml
Reverts h3mmy/bloopySphere#8479
=> Revert "Update Docker image ghcr.io/fluxcd/flux-manifests to v2.7.0"
